#
# Core properties for all profiles
#
spring.application.name=pan-user
spring.profiles.active=dev
#
server.port=9095
#
# OAuth2 Authorization Server — this app is the issuer
spring.security.oauth2.authorizationserver.issuer=http://localhost:9095
#
# springdoc
#
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=false
springdoc.packagesToScan=com.codingrodent.pan.user.controller
#
logging.level.com.codingrodent.pan.user=DEBUG

